spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/thrift_store
spring.datasource.username=root
spring.datasource.password=3754

jwt.secret=8f9aKJH#@!sdf8923jklsdf9u23rjklasfsarahbenabed

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sarabenabed9@gmail.com
spring.mail.password=egqgrfsxchfjtwps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true